/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Class {
    id: bigint;
    name: string;
    section: string;
}
export interface FeeRecord {
    studentId: bigint;
    date: Uint8Array;
    feeType: FeeType;
    isPaid: boolean;
    totalDue: bigint;
    amountPaid: bigint;
    receiptNo: string;
}
export interface SchoolInfo {
    principal: string;
    yearEstablished: bigint;
    name: string;
    email: string;
    logoUrl: string;
    affiliation: string;
}
export interface AdmitCard {
    studentId: bigint;
    examSchedule: string;
}
export type FeeType = {
    __kind__: "other";
    other: string;
} | {
    __kind__: "transport";
    transport: null;
} | {
    __kind__: "tuition";
    tuition: null;
} | {
    __kind__: "admission";
    admission: null;
};
export interface ExamResult {
    totalMarks: bigint;
    studentId: bigint;
    subject: string;
    marksObtained: bigint;
    examName: string;
}
export interface AttendanceRecord {
    status: AttendanceStatus;
    studentId: bigint;
    date: Uint8Array;
}
export interface Teacher {
    signature: string;
    subject: string;
    name: string;
}
export interface UserProfile {
    name: string;
    role: string;
    email: string;
}
export interface Student {
    dob: Uint8Array;
    name: string;
    motherName: string;
    photoUrl: string;
    classId: bigint;
    fatherName: string;
    address: string;
    admissionNo: string;
    phone: string;
    rollNo: bigint;
}
export enum AttendanceStatus {
    present = "present",
    late = "late",
    absent = "absent"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addExamResult(result: ExamResult): Promise<void>;
    addStudent(student: Student): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createClass(name: string, section: string): Promise<bigint>;
    generateAdmitCard(studentId: bigint, examSchedule: string): Promise<void>;
    getAdmitCard(studentId: bigint): Promise<AdmitCard>;
    getAttendance(studentId: bigint): Promise<Array<AttendanceRecord>>;
    getAttendanceByClassAndDate(classId: bigint, date: Uint8Array): Promise<Array<[bigint, AttendanceStatus]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClass(classId: bigint): Promise<Class | null>;
    getResultSummary(studentId: bigint, examName: string): Promise<{
        totalMarks: bigint;
        results: Array<ExamResult>;
        obtainedMarks: bigint;
        percentage: number;
    }>;
    getSchoolInfo(): Promise<SchoolInfo>;
    getStudent(studentId: bigint): Promise<Student>;
    getStudentFees(studentId: bigint): Promise<Array<FeeRecord>>;
    getStudentResults(studentId: bigint): Promise<Array<ExamResult>>;
    getTeacher(teacherId: Principal): Promise<Teacher | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listAllStudents(): Promise<Array<Student>>;
    listClasses(): Promise<Array<Class>>;
    listStudentsByClass(classId: bigint): Promise<Array<Student>>;
    listTeachers(): Promise<Array<[Principal, Teacher]>>;
    markAttendance(studentId: bigint, status: AttendanceStatus): Promise<void>;
    recordFeePayment(studentId: bigint, amountPaid: bigint, totalDue: bigint, feeType: FeeType): Promise<void>;
    registerTeacher(teacher: Teacher): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updatePaymentStatus(studentId: bigint, receiptNo: string, isPaid: boolean): Promise<void>;
    updateStudent(studentId: bigint, student: Student): Promise<void>;
    updateTeacher(teacher: Teacher): Promise<void>;
}
import type { AttendanceRecord as _AttendanceRecord, AttendanceStatus as _AttendanceStatus, Class as _Class, FeeRecord as _FeeRecord, FeeType as _FeeType, Teacher as _Teacher, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addExamResult(arg0: ExamResult): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addExamResult(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExamResult(arg0);
            return result;
        }
    }
    async addStudent(arg0: Student): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStudent(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createClass(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createClass(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClass(arg0, arg1);
            return result;
        }
    }
    async generateAdmitCard(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.generateAdmitCard(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateAdmitCard(arg0, arg1);
            return result;
        }
    }
    async getAdmitCard(arg0: bigint): Promise<AdmitCard> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdmitCard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdmitCard(arg0);
            return result;
        }
    }
    async getAttendance(arg0: bigint): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendance(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendance(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAttendanceByClassAndDate(arg0: bigint, arg1: Uint8Array): Promise<Array<[bigint, AttendanceStatus]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceByClassAndDate(arg0, arg1);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceByClassAndDate(arg0, arg1);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClass(arg0: bigint): Promise<Class | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getClass(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClass(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResultSummary(arg0: bigint, arg1: string): Promise<{
        totalMarks: bigint;
        results: Array<ExamResult>;
        obtainedMarks: bigint;
        percentage: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getResultSummary(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResultSummary(arg0, arg1);
            return result;
        }
    }
    async getSchoolInfo(): Promise<SchoolInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.getSchoolInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSchoolInfo();
            return result;
        }
    }
    async getStudent(arg0: bigint): Promise<Student> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudent(arg0);
            return result;
        }
    }
    async getStudentFees(arg0: bigint): Promise<Array<FeeRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentFees(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentFees(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentResults(arg0: bigint): Promise<Array<ExamResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentResults(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentResults(arg0);
            return result;
        }
    }
    async getTeacher(arg0: Principal): Promise<Teacher | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeacher(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeacher(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllStudents(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllStudents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllStudents();
            return result;
        }
    }
    async listClasses(): Promise<Array<Class>> {
        if (this.processError) {
            try {
                const result = await this.actor.listClasses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listClasses();
            return result;
        }
    }
    async listStudentsByClass(arg0: bigint): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.listStudentsByClass(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listStudentsByClass(arg0);
            return result;
        }
    }
    async listTeachers(): Promise<Array<[Principal, Teacher]>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTeachers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTeachers();
            return result;
        }
    }
    async markAttendance(arg0: bigint, arg1: AttendanceStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAttendance(arg0, to_candid_AttendanceStatus_n20(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAttendance(arg0, to_candid_AttendanceStatus_n20(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async recordFeePayment(arg0: bigint, arg1: bigint, arg2: bigint, arg3: FeeType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordFeePayment(arg0, arg1, arg2, to_candid_FeeType_n22(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordFeePayment(arg0, arg1, arg2, to_candid_FeeType_n22(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async registerTeacher(arg0: Teacher): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerTeacher(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerTeacher(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updatePaymentStatus(arg0: bigint, arg1: string, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePaymentStatus(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePaymentStatus(arg0, arg1, arg2);
            return result;
        }
    }
    async updateStudent(arg0: bigint, arg1: Student): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudent(arg0, arg1);
            return result;
        }
    }
    async updateTeacher(arg0: Teacher): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeacher(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeacher(arg0);
            return result;
        }
    }
}
function from_candid_AttendanceRecord_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceRecord): AttendanceRecord {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_AttendanceStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceStatus): AttendanceStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_FeeRecord_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeeRecord): FeeRecord {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_FeeType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeeType): FeeType {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Class]): Class | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Teacher]): Teacher | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studentId: bigint;
    date: Uint8Array;
    feeType: _FeeType;
    isPaid: boolean;
    totalDue: bigint;
    amountPaid: bigint;
    receiptNo: string;
}): {
    studentId: bigint;
    date: Uint8Array;
    feeType: FeeType;
    isPaid: boolean;
    totalDue: bigint;
    amountPaid: bigint;
    receiptNo: string;
} {
    return {
        studentId: value.studentId,
        date: value.date,
        feeType: from_candid_FeeType_n17(_uploadFile, _downloadFile, value.feeType),
        isPaid: value.isPaid,
        totalDue: value.totalDue,
        amountPaid: value.amountPaid,
        receiptNo: value.receiptNo
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _AttendanceStatus;
    studentId: bigint;
    date: Uint8Array;
}): {
    status: AttendanceStatus;
    studentId: bigint;
    date: Uint8Array;
} {
    return {
        status: from_candid_AttendanceStatus_n6(_uploadFile, _downloadFile, value.status),
        studentId: value.studentId,
        date: value.date
    };
}
function from_candid_tuple_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, _AttendanceStatus]): [bigint, AttendanceStatus] {
    return [
        value[0],
        from_candid_AttendanceStatus_n6(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: string;
} | {
    transport: null;
} | {
    tuition: null;
} | {
    admission: null;
}): {
    __kind__: "other";
    other: string;
} | {
    __kind__: "transport";
    transport: null;
} | {
    __kind__: "tuition";
    tuition: null;
} | {
    __kind__: "admission";
    admission: null;
} {
    return "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "transport" in value ? {
        __kind__: "transport",
        transport: value.transport
    } : "tuition" in value ? {
        __kind__: "tuition",
        tuition: value.tuition
    } : "admission" in value ? {
        __kind__: "admission",
        admission: value.admission
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    present: null;
} | {
    late: null;
} | {
    absent: null;
}): AttendanceStatus {
    return "present" in value ? AttendanceStatus.present : "late" in value ? AttendanceStatus.late : "absent" in value ? AttendanceStatus.absent : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FeeRecord>): Array<FeeRecord> {
    return value.map((x)=>from_candid_FeeRecord_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AttendanceRecord>): Array<AttendanceRecord> {
    return value.map((x)=>from_candid_AttendanceRecord_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, _AttendanceStatus]>): Array<[bigint, AttendanceStatus]> {
    return value.map((x)=>from_candid_tuple_n9(_uploadFile, _downloadFile, x));
}
function to_candid_AttendanceStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): _AttendanceStatus {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_FeeType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeeType): _FeeType {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): {
    present: null;
} | {
    late: null;
} | {
    absent: null;
} {
    return value == AttendanceStatus.present ? {
        present: null
    } : value == AttendanceStatus.late ? {
        late: null
    } : value == AttendanceStatus.absent ? {
        absent: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "other";
    other: string;
} | {
    __kind__: "transport";
    transport: null;
} | {
    __kind__: "tuition";
    tuition: null;
} | {
    __kind__: "admission";
    admission: null;
}): {
    other: string;
} | {
    transport: null;
} | {
    tuition: null;
} | {
    admission: null;
} {
    return value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "transport" ? {
        transport: value.transport
    } : value.__kind__ === "tuition" ? {
        tuition: value.tuition
    } : value.__kind__ === "admission" ? {
        admission: value.admission
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
