/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdmitCard { 'studentId' : bigint, 'examSchedule' : string }
export interface AttendanceRecord {
  'status' : AttendanceStatus,
  'studentId' : bigint,
  'date' : Uint8Array,
}
export type AttendanceStatus = { 'present' : null } |
  { 'late' : null } |
  { 'absent' : null };
export interface Class { 'id' : bigint, 'name' : string, 'section' : string }
export interface ExamResult {
  'totalMarks' : bigint,
  'studentId' : bigint,
  'subject' : string,
  'marksObtained' : bigint,
  'examName' : string,
}
export interface FeeRecord {
  'studentId' : bigint,
  'date' : Uint8Array,
  'feeType' : FeeType,
  'isPaid' : boolean,
  'totalDue' : bigint,
  'amountPaid' : bigint,
  'receiptNo' : string,
}
export type FeeType = { 'other' : string } |
  { 'transport' : null } |
  { 'tuition' : null } |
  { 'admission' : null };
export interface SchoolInfo {
  'principal' : string,
  'yearEstablished' : bigint,
  'name' : string,
  'email' : string,
  'logoUrl' : string,
  'affiliation' : string,
}
export interface Student {
  'dob' : Uint8Array,
  'name' : string,
  'motherName' : string,
  'photoUrl' : string,
  'classId' : bigint,
  'fatherName' : string,
  'address' : string,
  'admissionNo' : string,
  'phone' : string,
  'rollNo' : bigint,
}
export interface Teacher {
  'signature' : string,
  'subject' : string,
  'name' : string,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addExamResult' : ActorMethod<[ExamResult], undefined>,
  'addStudent' : ActorMethod<[Student], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createClass' : ActorMethod<[string, string], bigint>,
  'generateAdmitCard' : ActorMethod<[bigint, string], undefined>,
  'getAdmitCard' : ActorMethod<[bigint], AdmitCard>,
  'getAttendance' : ActorMethod<[bigint], Array<AttendanceRecord>>,
  'getAttendanceByClassAndDate' : ActorMethod<
    [bigint, Uint8Array],
    Array<[bigint, AttendanceStatus]>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClass' : ActorMethod<[bigint], [] | [Class]>,
  'getResultSummary' : ActorMethod<
    [bigint, string],
    {
      'totalMarks' : bigint,
      'results' : Array<ExamResult>,
      'obtainedMarks' : bigint,
      'percentage' : number,
    }
  >,
  'getSchoolInfo' : ActorMethod<[], SchoolInfo>,
  'getStudent' : ActorMethod<[bigint], Student>,
  'getStudentFees' : ActorMethod<[bigint], Array<FeeRecord>>,
  'getStudentResults' : ActorMethod<[bigint], Array<ExamResult>>,
  'getTeacher' : ActorMethod<[Principal], [] | [Teacher]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllStudents' : ActorMethod<[], Array<Student>>,
  'listClasses' : ActorMethod<[], Array<Class>>,
  'listStudentsByClass' : ActorMethod<[bigint], Array<Student>>,
  'listTeachers' : ActorMethod<[], Array<[Principal, Teacher]>>,
  'markAttendance' : ActorMethod<[bigint, AttendanceStatus], undefined>,
  'recordFeePayment' : ActorMethod<
    [bigint, bigint, bigint, FeeType],
    undefined
  >,
  'registerTeacher' : ActorMethod<[Teacher], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updatePaymentStatus' : ActorMethod<[bigint, string, boolean], undefined>,
  'updateStudent' : ActorMethod<[bigint, Student], undefined>,
  'updateTeacher' : ActorMethod<[Teacher], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];