/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ExamResult = IDL.Record({
  'totalMarks' : IDL.Nat,
  'studentId' : IDL.Nat,
  'subject' : IDL.Text,
  'marksObtained' : IDL.Nat,
  'examName' : IDL.Text,
});
export const Student = IDL.Record({
  'dob' : IDL.Vec(IDL.Nat8),
  'name' : IDL.Text,
  'motherName' : IDL.Text,
  'photoUrl' : IDL.Text,
  'classId' : IDL.Nat,
  'fatherName' : IDL.Text,
  'address' : IDL.Text,
  'admissionNo' : IDL.Text,
  'phone' : IDL.Text,
  'rollNo' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdmitCard = IDL.Record({
  'studentId' : IDL.Nat,
  'examSchedule' : IDL.Text,
});
export const AttendanceStatus = IDL.Variant({
  'present' : IDL.Null,
  'late' : IDL.Null,
  'absent' : IDL.Null,
});
export const AttendanceRecord = IDL.Record({
  'status' : AttendanceStatus,
  'studentId' : IDL.Nat,
  'date' : IDL.Vec(IDL.Nat8),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
});
export const Class = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'section' : IDL.Text,
});
export const SchoolInfo = IDL.Record({
  'principal' : IDL.Text,
  'yearEstablished' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'logoUrl' : IDL.Text,
  'affiliation' : IDL.Text,
});
export const FeeType = IDL.Variant({
  'other' : IDL.Text,
  'transport' : IDL.Null,
  'tuition' : IDL.Null,
  'admission' : IDL.Null,
});
export const FeeRecord = IDL.Record({
  'studentId' : IDL.Nat,
  'date' : IDL.Vec(IDL.Nat8),
  'feeType' : FeeType,
  'isPaid' : IDL.Bool,
  'totalDue' : IDL.Nat,
  'amountPaid' : IDL.Nat,
  'receiptNo' : IDL.Text,
});
export const Teacher = IDL.Record({
  'signature' : IDL.Text,
  'subject' : IDL.Text,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addExamResult' : IDL.Func([ExamResult], [], []),
  'addStudent' : IDL.Func([Student], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createClass' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'generateAdmitCard' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'getAdmitCard' : IDL.Func([IDL.Nat], [AdmitCard], ['query']),
  'getAttendance' : IDL.Func([IDL.Nat], [IDL.Vec(AttendanceRecord)], ['query']),
  'getAttendanceByClassAndDate' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Nat8)],
      [IDL.Vec(IDL.Tuple(IDL.Nat, AttendanceStatus))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClass' : IDL.Func([IDL.Nat], [IDL.Opt(Class)], ['query']),
  'getResultSummary' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [
        IDL.Record({
          'totalMarks' : IDL.Nat,
          'results' : IDL.Vec(ExamResult),
          'obtainedMarks' : IDL.Nat,
          'percentage' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getSchoolInfo' : IDL.Func([], [SchoolInfo], ['query']),
  'getStudent' : IDL.Func([IDL.Nat], [Student], ['query']),
  'getStudentFees' : IDL.Func([IDL.Nat], [IDL.Vec(FeeRecord)], ['query']),
  'getStudentResults' : IDL.Func([IDL.Nat], [IDL.Vec(ExamResult)], ['query']),
  'getTeacher' : IDL.Func([IDL.Principal], [IDL.Opt(Teacher)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'listClasses' : IDL.Func([], [IDL.Vec(Class)], ['query']),
  'listStudentsByClass' : IDL.Func([IDL.Nat], [IDL.Vec(Student)], ['query']),
  'listTeachers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, Teacher))],
      ['query'],
    ),
  'markAttendance' : IDL.Func([IDL.Nat, AttendanceStatus], [], []),
  'recordFeePayment' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, FeeType], [], []),
  'registerTeacher' : IDL.Func([Teacher], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updatePaymentStatus' : IDL.Func([IDL.Nat, IDL.Text, IDL.Bool], [], []),
  'updateStudent' : IDL.Func([IDL.Nat, Student], [], []),
  'updateTeacher' : IDL.Func([Teacher], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ExamResult = IDL.Record({
    'totalMarks' : IDL.Nat,
    'studentId' : IDL.Nat,
    'subject' : IDL.Text,
    'marksObtained' : IDL.Nat,
    'examName' : IDL.Text,
  });
  const Student = IDL.Record({
    'dob' : IDL.Vec(IDL.Nat8),
    'name' : IDL.Text,
    'motherName' : IDL.Text,
    'photoUrl' : IDL.Text,
    'classId' : IDL.Nat,
    'fatherName' : IDL.Text,
    'address' : IDL.Text,
    'admissionNo' : IDL.Text,
    'phone' : IDL.Text,
    'rollNo' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdmitCard = IDL.Record({
    'studentId' : IDL.Nat,
    'examSchedule' : IDL.Text,
  });
  const AttendanceStatus = IDL.Variant({
    'present' : IDL.Null,
    'late' : IDL.Null,
    'absent' : IDL.Null,
  });
  const AttendanceRecord = IDL.Record({
    'status' : AttendanceStatus,
    'studentId' : IDL.Nat,
    'date' : IDL.Vec(IDL.Nat8),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  const Class = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'section' : IDL.Text,
  });
  const SchoolInfo = IDL.Record({
    'principal' : IDL.Text,
    'yearEstablished' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'logoUrl' : IDL.Text,
    'affiliation' : IDL.Text,
  });
  const FeeType = IDL.Variant({
    'other' : IDL.Text,
    'transport' : IDL.Null,
    'tuition' : IDL.Null,
    'admission' : IDL.Null,
  });
  const FeeRecord = IDL.Record({
    'studentId' : IDL.Nat,
    'date' : IDL.Vec(IDL.Nat8),
    'feeType' : FeeType,
    'isPaid' : IDL.Bool,
    'totalDue' : IDL.Nat,
    'amountPaid' : IDL.Nat,
    'receiptNo' : IDL.Text,
  });
  const Teacher = IDL.Record({
    'signature' : IDL.Text,
    'subject' : IDL.Text,
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addExamResult' : IDL.Func([ExamResult], [], []),
    'addStudent' : IDL.Func([Student], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createClass' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'generateAdmitCard' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'getAdmitCard' : IDL.Func([IDL.Nat], [AdmitCard], ['query']),
    'getAttendance' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getAttendanceByClassAndDate' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Nat8)],
        [IDL.Vec(IDL.Tuple(IDL.Nat, AttendanceStatus))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClass' : IDL.Func([IDL.Nat], [IDL.Opt(Class)], ['query']),
    'getResultSummary' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [
          IDL.Record({
            'totalMarks' : IDL.Nat,
            'results' : IDL.Vec(ExamResult),
            'obtainedMarks' : IDL.Nat,
            'percentage' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getSchoolInfo' : IDL.Func([], [SchoolInfo], ['query']),
    'getStudent' : IDL.Func([IDL.Nat], [Student], ['query']),
    'getStudentFees' : IDL.Func([IDL.Nat], [IDL.Vec(FeeRecord)], ['query']),
    'getStudentResults' : IDL.Func([IDL.Nat], [IDL.Vec(ExamResult)], ['query']),
    'getTeacher' : IDL.Func([IDL.Principal], [IDL.Opt(Teacher)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'listClasses' : IDL.Func([], [IDL.Vec(Class)], ['query']),
    'listStudentsByClass' : IDL.Func([IDL.Nat], [IDL.Vec(Student)], ['query']),
    'listTeachers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, Teacher))],
        ['query'],
      ),
    'markAttendance' : IDL.Func([IDL.Nat, AttendanceStatus], [], []),
    'recordFeePayment' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, FeeType], [], []),
    'registerTeacher' : IDL.Func([Teacher], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updatePaymentStatus' : IDL.Func([IDL.Nat, IDL.Text, IDL.Bool], [], []),
    'updateStudent' : IDL.Func([IDL.Nat, Student], [], []),
    'updateTeacher' : IDL.Func([Teacher], [], []),
  });
};

export const init = ({ IDL }) => { return []; };